from annoying.decorators import render_to
from fack.models import Question, Topic

@render_to("ka_lite/faq.html")
def faq(request):
	"""Render FAQ generated by django-fack backend (override django-fack styles)"""
	topics = Topic.objects.all()
	context = {}
	for t in topics: 
		context[t] = Question.objects.filter(topic=t).active()

	return {"faq": context}
